version: '3.8'

services:
  mysqlsvc:
    image: mysqlsvc:v0
    restart: always
    build:
      context: mysql-hydrated-db/
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"

  gosvc:
    image: gosvc:v0
    restart: always
    build:
      context: golang-webserver/example/
    ports:
      - "8000:10000"

  nodesvc:
    image: nodesvc:v0
    restart: always
    build:
      context: node-express-webserver/example/
    ports:
      - "8001:8001"

  ionicsvc:
    image: ionicsvc:v0
    restart: always
    build:
      context: ionic-angular-spa/example/
    ports:
      - "8080:80"
    links:
      - javasvc
      - nodesvc
    depends_on:
      - javasvc
      - nodesvc
    labels:
      kompose.service.type: LoadBalancer

  javasvc:
    image: javasvc:v0
    restart: always
    build:
      context: java-spring-boot-maven/example
    ports:
      - "8002:8080"

  pythondjangosvc:
    image: pythondjangosvc:v0
    restart: always
    build:
      context: python-django-webserver/example
    ports:
      - "8005:8005"

  pythonflasksvc:
    image: pythonflasksvc:v0
    restart: always
    build:
      context: python-flask-webserver/example
    ports:
      - "8003:5000"

  pythonhttpsvc:
    image: pythonhttpsvc:v0
    restart: always
    build:
      context: python-http-webserver/example
    ports:
      - "8004:8004"

  dotnetwebsvc:
    image: dotnetwebsvc:v0
    restart: always
    build:
      context: dot-net-web/example
    ports:
      - "8006:80"

  dotnetmvcsvc:
    image: dotnetmvcsvc:v0
    restart: always
    build:
      context: dot-net-mvc/example
    ports:
      - "8007:8007"

  phpwebsvc:
    image: phpwebsvc:v0
    restart: always
    build:
      context: php-webserver/example
    ports:
      - "8008:8008"

  phplaravel9svc:
    image: phplaravel9svc:v0
    restart: always
    build:
      context: php-laravel9/
    ports:
      - "8009:8009"
